version: "3.9"
services:
  web:
    build: .
    depends_on:
      - mama
      - redis
    ports:
      - "8000:5000"
  mama:
    build: 
      dockerfile: server/Dockerfile
      context: ..
    ports:
      - "50051:50051"
  redis:
    image: "redis:7.0.7-alpine3.17"
