version: "3.9"
services:
  web:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAMA_HOST=mama
      - MAMA_PORT=50051    
    depends_on:
      - mama
      - redis
    ports:
      - "8000:5000"
  # TODO: pass path to tiles
  mama:
    build: 
      dockerfile: server/Dockerfile
      context: ..
    ports:
      - "50051:50051"
  redis:
    image: "redis:7.0.7-alpine3.17"
