version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  mama:
    build: 
      dockerfile: server/Dockerfile
      context: ..
    ports:
      - "8001:50051"
  redis:
    image: "redis:7.0.7-alpine3.17"
