name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # format:
  #   runs-on: ubuntu-22.04
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Check format
  #     run: |
  #       sudo apt-get update -y && sudo apt-get -y install clang-format-15
  #       ./scripts/format.sh
  docker:
   # needs: format
    runs-on: ubuntu-22.04
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: server/Dockerfile
        push: true
        platforms: ${{ (github.ref == 'refs/heads/main' && github.event_name != 'pull_request') && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Test Docker Image
      run: |
        DOCKER_IMAGE_NAME="${{ steps.meta.outputs.tags }}"
        mkdir tiles
        cd tiles
        # download OSM data
        wget -q http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf
        # generate mama tiles
        docker run -t -v $(pwd):/tiles $DOCKER_IMAGE_NAME tilegen /tiles/berlin-latest.osm.pbf /tiles
        # run mama-server
        docker run --network=host --name=mama-container --rm -t -p 50051:50051 -v $(pwd):/tiles $DOCKER_IMAGE_NAME mama_server /tiles &

        sleep 10
        docker run --add-host host.docker.internal:host-gateway fullstorydev/grpcurl -plaintext -d '{"entries": [{"location": {"latitude": 52.517037, "longitude": 13.388860}}]}' host.docker.internal:50051 mama.server.api.MamaService.Match
        # TODO: call grpc
        docker stop mama-container

  # build:
  #   needs: format
  #   runs-on: ubuntu-22.04
  #   env: 
  #     CXX: 'clang++-14'
  #     CC: 'clang-14'
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       submodules: 'recursive'
  #   - name: Install dependencies
  #     run: |
  #       sudo apt-get update -y
  #       sudo apt-get install protobuf-compiler \
  #                            libprotoc-dev \
  #                            libprotobuf-dev
  #   - name: Build
  #     run: |
  #       mkdir build
  #       cd build
  #       cmake -DCMAKE_BUILD_TYPE=Release ..
  #       make -j8
  #   - name: Build server
  #     run: |
  #       mkdir -p server/build
  #       cd server/build
  #       cmake -DCMAKE_BUILD_TYPE=Release ..
  #       make -j8
  #   - name: Run tests
  #     run: |
  #       # run tests without shortest path table
  #       mkdir tiles
  #       ./build/tilegen test/data/monaco-latest.osm.pbf tiles
  #       TILES_FOLDER=tiles ./build/tests   
  #       rm -rf tiles

  #       # run tests with shortest path table
  #       mkdir tiles
  #       ./build/tilegen test/data/monaco-latest.osm.pbf tiles --max-precompute-path-length 250
  #       TILES_FOLDER=tiles ./build/tests     
  #       rm -rf tiles

  # demo:
  #   needs: format
  #   runs-on: ubuntu-22.04
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       submodules: 'recursive'
  #   - name: Check protos
  #     run: cmp --silent server/mama.proto demo/protos/mama.proto || (echo "Demo and server use different protos" && exit 1)
  #   - name: Build
  #     run: |
  #       sudo apt-get update -y && sudo apt-get install osmium-tool
  #       cd demo && ./build.sh
  #   - name: Test
  #     run: |
  #       cd demo && ./test.sh
  #   - name: Benchmark
  #     run: |
  #       cd demo && npm install && ./benchmark.sh
    

         
