name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-2204

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j8
        